export const jobData = [
    {
        id: 1,
        image: 'src/Assets/aqua.png',
        title: 'Frontend Developer',
        time: '2 Days',
        location: 'Canada',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti, laboriosam!',
        company: 'Aqua Corp.',
    },
    {
        id: 2,
        image: 'src/Assets/astor.png',
        title: 'Backend Developer',
        time: 'Now',
        location: 'Depok',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti, laboriosam!',
        company: 'PT Astor Sejahtera',
    },
    {
        id: 3,
        image: 'src/Assets/tokopedia.png',
        title: 'Fullstack Developer',
        time: '4H',
        location: 'Cibubur',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti, laboriosam!',
        company: 'Tokopedia.inc',
    },
    {
        id: 4,
        image: 'src/Assets/cocacola.png',
        title: 'Pemasok Air',
        time: 'Now',
        location: 'Citayam',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti, laboriosam!',
        company: 'The Coca-Cola Company',
    },
]